version: "3.9"
services:
  ingest:
    build: .
    environment:
      - AZURE_CLIENT_ID=2254675d-f031-4623-95b3-53948cbde732
      - AZURE_CLIENT_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL3ZhdWx0LmF6dXJlLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2NiZDFiNDA2LTU3MzAtNDgzOS05NTZmLTRiZThjNDJiMjI0ZS8iLCJpYXQiOjE2NzM2MzMwNzYsIm5iZiI6MTY3MzYzMzA3NiwiZXhwIjoxNjczNjM3Nzk3LCJhY3IiOiIxIiwiYWlvIjoiQVlRQWUvOFRBQUFBRXdrQ1BiZTlORnczUU9JOHhlVDNCQXBITGxVQnlyc3ZyOE9jLzJuaGhnc0JYVFJ0Y3piNzh2NXl3WjhIV0RjTlBZenhLbk9hNW1kNFdTelNvYUhUdDB0SGJJZktKcUZwTkFoUjdzM3pERmRraXcxTkhoR0NlMm9ETENnem11RzFnbUM4RVF4ckVZY1NDVE9Sa3E3VjVaaWVjOWtsUkNyOVIvQnFyUnJHQmZjPSIsImFsdHNlY2lkIjoiMTpsaXZlLmNvbTowMDAzN0ZGRTQxODM3MjgzIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6ImI2NzdjMjkwLWNmNGItNGE4ZS1hNjBlLTkxYmE2NTBhNGFiZSIsImFwcGlkYWNyIjoiMiIsImVtYWlsIjoiY2Fyb2xpbmUucmVpbmlnQGdtYWlsLmNvbSIsImZhbWlseV9uYW1lIjoiUmVpbmlnIiwiZ2l2ZW5fbmFtZSI6ImNhcm9saW5lIiwiZ3JvdXBzIjpbImQyODk4YjYyLWU1M2EtNDBhYS05MWJkLTJhMzc1ZWU1YjdjYSJdLCJpZHAiOiJsaXZlLmNvbSIsImlwYWRkciI6IjM3LjE5MS4yNDEuNzciLCJuYW1lIjoiY2Fyb2xpbmUgUmVpbmlnIiwib2lkIjoiYWE3NTA2NjUtMmI0ZS00ZmQ5LWJhZDAtZTg4ODQ1MDQxZTdiIiwicHVpZCI6IjEwMDMyMDAxRkQ0NjYyMDYiLCJyaCI6IjAuQVhrQUJyVFJ5ekJYT1VpVmIwdm94Q3NpVGptenFNLWlnaHBIbzhrUHdMNTZRSk9VQUJFLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjVTODlXd0l1QzlkZnpJWUFZZGNmQ29GUWdiRG53QmRpeDN2UTRaMFcxT00iLCJ0aWQiOiJjYmQxYjQwNi01NzMwLTQ4MzktOTU2Zi00YmU4YzQyYjIyNGUiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2Nhcm9saW5lLnJlaW5pZ0BnbWFpbC5jb20iLCJ1dGkiOiJXS3kyYnRnTG8wR2lCYmNhcXVRZEFBIiwidmVyIjoiMS4wIn0.O1E0veBdpNzjlU7AgcEmS9Y6ltk9W7ZoCu0OIqHsYvHFPEr-w4SujbSPu3Sxi8MQZguaiFTYqAMVZH8ft-IhZzKE7D_7NU5IW7cmtk_AOJxjlbh5ZaL4-O1gjKOifRUoK2pq1eObv_oEcMciQTRrDwsrri9hPAJcnBQswsZ0fvao-GWpD-gSmS34V6k3xzRrdKgMVuzeLyPKzl_QNjgLCpgivspH5gYNBn727zsVYafzfIEnvfOQh3DbSqRmysc2gcwPoe3DiXpyTDp5i_70J0tmU7elISSf1IcMp6yTHagIJM2jvP09wuozvl_SBogETk9Q0Htm-rZVtA2gIcbtbA      
      - AZURE_TENANT_ID=cbd1b406-5730-4839-956f-4be8c42b224e

  spark-master:
    image: apache/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    user: root
    command: /bin/bash -c "mkdir -p /opt/spark/logs/ && /opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*"
  
  spark-slave-1:
    image: apache/spark:latest
    ports:
      - "8181:8081"
    user: root
    command: /bin/bash -c "/opt/spark/sbin/start-slave.sh --webui-port 8081 spark://spark-master:7077  && tail -f /opt/spark/logs/*"
  
  spark-slave-2:
    image: apache/spark:latest
    ports:
      - "8182:8081"
    user: root
    command: /bin/bash -c "/opt/spark/sbin/start-slave.sh --webui-port 8081 spark://spark-master:7077  && tail -f /opt/spark/logs/*"

# az account get-access-token --resource=https://vault.azure.net