version: "3.9"
services:
  ingest:
    build:
      context: .
      dockerfile: Dockerfiles/ingestor.Dockerfile
    environment:
      - AZURE_CLIENT_ID=2254675d-f031-4623-95b3-53948cbde732
      - AZURE_CLIENT_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL3ZhdWx0LmF6dXJlLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2NiZDFiNDA2LTU3MzAtNDgzOS05NTZmLTRiZThjNDJiMjI0ZS8iLCJpYXQiOjE2NzM2MzMwNzYsIm5iZiI6MTY3MzYzMzA3NiwiZXhwIjoxNjczNjM3Nzk3LCJhY3IiOiIxIiwiYWlvIjoiQVlRQWUvOFRBQUFBRXdrQ1BiZTlORnczUU9JOHhlVDNCQXBITGxVQnlyc3ZyOE9jLzJuaGhnc0JYVFJ0Y3piNzh2NXl3WjhIV0RjTlBZenhLbk9hNW1kNFdTelNvYUhUdDB0SGJJZktKcUZwTkFoUjdzM3pERmRraXcxTkhoR0NlMm9ETENnem11RzFnbUM4RVF4ckVZY1NDVE9Sa3E3VjVaaWVjOWtsUkNyOVIvQnFyUnJHQmZjPSIsImFsdHNlY2lkIjoiMTpsaXZlLmNvbTowMDAzN0ZGRTQxODM3MjgzIiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6ImI2NzdjMjkwLWNmNGItNGE4ZS1hNjBlLTkxYmE2NTBhNGFiZSIsImFwcGlkYWNyIjoiMiIsImVtYWlsIjoiY2Fyb2xpbmUucmVpbmlnQGdtYWlsLmNvbSIsImZhbWlseV9uYW1lIjoiUmVpbmlnIiwiZ2l2ZW5fbmFtZSI6ImNhcm9saW5lIiwiZ3JvdXBzIjpbImQyODk4YjYyLWU1M2EtNDBhYS05MWJkLTJhMzc1ZWU1YjdjYSJdLCJpZHAiOiJsaXZlLmNvbSIsImlwYWRkciI6IjM3LjE5MS4yNDEuNzciLCJuYW1lIjoiY2Fyb2xpbmUgUmVpbmlnIiwib2lkIjoiYWE3NTA2NjUtMmI0ZS00ZmQ5LWJhZDAtZTg4ODQ1MDQxZTdiIiwicHVpZCI6IjEwMDMyMDAxRkQ0NjYyMDYiLCJyaCI6IjAuQVhrQUJyVFJ5ekJYT1VpVmIwdm94Q3NpVGptenFNLWlnaHBIbzhrUHdMNTZRSk9VQUJFLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjVTODlXd0l1QzlkZnpJWUFZZGNmQ29GUWdiRG53QmRpeDN2UTRaMFcxT00iLCJ0aWQiOiJjYmQxYjQwNi01NzMwLTQ4MzktOTU2Zi00YmU4YzQyYjIyNGUiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2Nhcm9saW5lLnJlaW5pZ0BnbWFpbC5jb20iLCJ1dGkiOiJXS3kyYnRnTG8wR2lCYmNhcXVRZEFBIiwidmVyIjoiMS4wIn0.O1E0veBdpNzjlU7AgcEmS9Y6ltk9W7ZoCu0OIqHsYvHFPEr-w4SujbSPu3Sxi8MQZguaiFTYqAMVZH8ft-IhZzKE7D_7NU5IW7cmtk_AOJxjlbh5ZaL4-O1gjKOifRUoK2pq1eObv_oEcMciQTRrDwsrri9hPAJcnBQswsZ0fvao-GWpD-gSmS34V6k3xzRrdKgMVuzeLyPKzl_QNjgLCpgivspH5gYNBn727zsVYafzfIEnvfOQh3DbSqRmysc2gcwPoe3DiXpyTDp5i_70J0tmU7elISSf1IcMp6yTHagIJM2jvP09wuozvl_SBogETk9Q0Htm-rZVtA2gIcbtbA      
      - AZURE_TENANT_ID=cbd1b406-5730-4839-956f-4be8c42b224e
    volumes:
      - ./data:/root/us-accidents
      - ./code:/root/code

  spark-master:
    build: 
      context: .
      dockerfile: Dockerfiles/spark-master.Dockerfile
    ports:
      - "8080:8080"
      - "7077:7077"
    user: root
    volumes:
      - ./log:/opt/spark/logs
      - ./data:/root/us-accidents
  
  spark-worker-1:
    build: 
      context: .
      dockerfile: Dockerfiles/spark-worker.Dockerfile
    ports:
      - "8181:8181"
      - "38081:38081"
    environment:
      - WEBUI_PORT=8181
      - WORKER_PORT=38081
    user: root
    volumes:
      - ./log:/opt/spark/logs
      - ./data:/root/us-accidents
  
  spark-worker-2:
    build: 
      context: .
      dockerfile: Dockerfiles/spark-worker.Dockerfile
    ports:
      - "8182:8182"
      - "38082:38082"
    environment:
      - WEBUI_PORT=8182
      - WORKER_PORT=38082
    user: root
    volumes:
      - ./log:/opt/spark/logs
      - ./data:/root/us-accidents