on:
  schedule:
   - cron:  '0 0 1 * *' # to run at 00:00 on the first day of every month
  repository_dispatch:
    types:
      - run
  workflow_dispatch:
name: Deploy and run pipeline
jobs:
  build-and-deploy-pipeline:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./devops/templates/pipeline.bicep
        failOnStdErr: false