on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./templates/main.bicep
        failOnStdErr: false

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build docker
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_ENDPOINT }}/ingestor:${{ github.sha }} -t ${{ secrets.ACR_ENDPOINT }}/ingestor:latest
        docker push -a ${{ secrets.ACR_ENDPOINT }}/ingestor

  build-and-deploy-pipeline:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./templates/pipeline.bicep
        failOnStdErr: false

      # Deploy to Azure container instances
    # - name: 'Deploy to Azure Container Instances'
    #   uses: 'azure/aci-deploy@v1'
    #   with:
    #     resource-group: ${{ secrets.AZURE_RG }}
    #     dns-name-label: ${{ secrets.AZURE_RG }}dns
    #     image: ${{ secrets.ACR_ENDPOINT }}/ingestor:latest
    #     registry-login-server: ${{ secrets.ACR_ENDPOINT }}
    #     registry-username: ${{ secrets.ACR_USERNAME }}
    #     registry-password: ${{ secrets.ACR_PASSWORD }}
    #     name: aci-dataengineering
    #     location: 'west europe'
