# on:
#  schedule:
#    - cron:  '0 0 1 * *' # to run at 00:00 on the first day of every month
on: [push]
name: Deploy and run pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./templates/pipeline.bicep
        failOnStdErr: false

      # Create Spark cluster
    # - name: 'Create HDInsight'
    #   uses: 'azure/aci-deploy@v1'
    #   with:
    #     resource-group: ${{ secrets.AZURE_RG }}
    #     template: ./main.bicep
    #      parameters: 'clusterName=dataEngineeringCluster storageSKU=Standard_LRS