# on:
#  schedule:
#    - cron:  '0 0 1 * *' # to run at 00:00 on the first day of every month
on: [push]
name: Deploy and run pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./templates/pipeline.bicep
        failOnStdErr: false

      # Deploy to Azure container instances
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.AZURE_RG }}
        dns-name-label: ${{ secrets.AZURE_RG }}dns
        image: ${{ secrets.ACR_ENDPOINT }}/ingestor:latest
        registry-login-server: ${{ secrets.ACR_ENDPOINT }}
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
        name: aci-dataengineering
        location: 'west europe'
